[tool.poetry]
name = "audio2midi"
version = "0.1.0"
description = ""
authors = ["Emanuele Di Lorenzo <emanuele.dilore@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
